### Autostart Services & Applications
exec_always gsettings set org.gnome.desktop.interface enable-animations false
exec waybar
exec mako
exec /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
