### General UI & Borders
default_border none

### Touchpad Gestures
bindgesture swipe:right workspace prev
bindgesture swipe:left workspace next

### Output Configuration
# Default wallpaper
output * bg ~/.config/sway/wallpaper/joyboy.png fill

### Input Devices Configuration
input type:keyboard {
    xkb_numlock enabled
}

input type:touchpad {
    dwt enabled
    tap enabled
    natural_scroll disable
    middle_emulation enabled
}
